Repository web42serv/webserv, pull requests merged in 2023-09, with the labels that each got.

#7 ✨ Feat: post method file upload
  html/cgiupload.py
  html/fileform.html
  src/http/CgiHandler.cpp
Labels: ✨ Feature

#21 ✨ Feat: directory 구조 수정 및 예외처리 추가
  YoupiBanane/directory/Yeah/not_happy.bad_extension
  YoupiBanane/directory/youpi.bad_extension
  bb.conf
  inc/Response.hpp
  src/http/Response.cpp
  src/server/HandleData.cpp
Labels: 🐞 Bug, ✅ Test, ✨ Feature

#26 🔨 Fix: Transfer-encoding: chunked 관련 HandleData 문제 해결
  .DS_Store
  bb.conf
  cgi_tester
  inc/Request.hpp
  inc/Webserv.hpp
  src/http/Request.cpp
  src/http/Response.cpp
  src/server/HandleData.cpp
  src/server/Webserv.cpp
  src/server/Worker.cpp
  webserv
Labels: 🐞 Bug

#27 🔨 Fix: RNRN error
  src/http/Request.cpp
  src/server/HandleData.cpp
Labels: 🐞 Bug
